### ISSUE TITLE
docs: change timestamp format

### ISSUE THREAD

**Issue by junghoon-vans** [dnd-side-project/dnd-8th-8-backend#123]
### Description

![스크린샷 2023-02-28 오전 2 02 38](https://user-images.githubusercontent.com/44942700/221630467-c115584c-ec65-42aa-b5fe-3c34ede4f789.png)

현재 문서화 페이지에 표기된 타임스탬프 형식을 배열에서 `String` 값으로 변경합니다.

- 체크리스트 아이템 등록/수정
- 예산표 등록/수정

### Solution

![스크린샷 2023-02-28 오전 2 05 25](https://user-images.githubusercontent.com/44942700/221630812-a20112f9-55d6-493e-9d15-3c630adee4ec.png)

스트링 값을 `parse` 하는 방법을 사용합니다.

**Comment by Chaerim1001** [comment]
parse를 사용하더라도 배열로 들어가게 되지 않나요?!
