### ISSUE TITLE
style: reorder annotation definition

### ISSUE THREAD

**Issue by junghoon-vans** [dnd-side-project/dnd-8th-8-backend#139]
### Description

어노테이션의 정렬이 일관되지 않아 가독성이 좋지 못한 문제가 발생합니다.

### Solution

어노테이션을 정의하는 순서를 정의하도록 합니다.

**Comment by Chaerim1001** [comment]
**1st**
`Controller`, `Service`, `Entity` 등 클래스의 주요 어노테이션

**2nd**
`RequestMapping` 등 주요 어노테이션과 연관된 어노테이션

**3rd**
`Getter` - `Setter` - `Constructor`
