### ISSUE TITLE
feat: add get current budget api

### ISSUE THREAD

**Issue by Chaerim1001** [dnd-side-project/dnd-8th-8-backend#149]
### Description

거래 내역 등록, 수정, 삭제 시 자동으로 결혼 예산이 변경되어야 합니다.

### Solution

현재 남아있는 결혼 자금을 조회할 수 있는 API를 추가합니다.

**Comment by junghoon-vans** [comment]
@Chaerim1001 추가되는 API 엔드포인트는 `/api/v1/budget` 을 사용하는 건 어떨까요

**Comment by Chaerim1001** [comment]
@junghoon-vans API를 추가하지 않고 기존에 있는 예산 API가 호출되었을 때 함께 계산하는 로직을 추가하면 어떨까요?

**Comment by junghoon-vans** [comment]
@Chaerim1001 기존 API라면 `api/v1/wedding/budget` 말씀하시는 건가요?
해당 API는 결혼 자금을 의미하는거라 해당 API와는 분리가 필요할 거 같아요

**Comment by Chaerim1001** [comment]
@junghoon-vans 아 제가 말한 건 결혼 자금 조회 API였어요. **GET** `api/v1/wedding/budget` 했을 때 거래 내역에 따라 +-를 계산해서 현재 남은 자금을 반환해 주는 방식으로 생각했습니다!

**Comment by junghoon-vans** [comment]
@Chaerim1001 초기 결혼 자금을 DB 상에서 가지고 있을 필요가 있을 거 같아요. 나중에 초기 자금을 수정하려고 할 때 +-가 계산되어 있는 잔금이라면 오히려 로직 처리가 어려워질 거 같아요.

**Comment by Chaerim1001** [comment]
@junghoon-vans 저도 초기 결혼 자금 데이터는 저장해두는 게 좋다고 생각해요. 그래서 초기 자금을 넣어두고 값을 수정하는 게 아니라 계산만 해서 프론트로 전달하는 방식을 생각했던건데 정훈님 말씀처럼 따로 API를 만드는 게 더 깔끔하겠네요!
